### ISSUE TITLE
Only generate HTML report on demand

### ISSUE THREAD

**Issue by thekid** [xp-forge/coverage#4]
Now that we have a summary display via #2, we could make generating the HTML report optional. Or maybe add an option to turn it off.

What do you think, @OlafSeng?

**Comment by OlafSeng** [comment]
Sure, I think it's a good idea to make the HTML report optional. 

But I am still wondering what the default output should be. I would be prefer a file based summary, e.g. like [this](https://github.com/istanbuljs/nyc#running-reports).  And then maybe add an option to have only a summary for all files.

**Comment by thekid** [comment]
Here's an idea:


![image](https://user-images.githubusercontent.com/696742/45647291-cdddf800-bac5-11e8-93b7-0d0136305c3a.png)

**Comment by OlafSeng** [comment]
Looks good!

**Comment by thekid** [comment]
So how about the following:

* We add the above output as default
* The current really short output can be used with `--summary` or something
* The HTML report is off by default, and can be activated with `--report[=directory]`

**Comment by thekid** [comment]
Released in https://github.com/xp-forge/coverage/releases/tag/v0.3.0
